spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/spring_batch
#    username: root
#    password: 12345
  datasource:
    url: jdbc:h2:mem:spring_batch
    driverClassName: org.h2.Driver
    username: sa
    password: 12345
  batch:
    initialize-schema: always

